#ifndef LOCAL2_H
#define LOCAL2_H
int lineid();
int myreader();
int setregs();
int eobl2();
int nextcook();
int cbgen();
int gencall();
int genscall();
int lastchance();
int rewfld();
int szty();
int shltype();
int spsz();
int shumul();
int special();
int shtemp();
int flshape();
void zzzcode();
void adrcon();
void hopcode();
void conput();
void insput();
void upput();
void adrput();
void acon();
int callreg();
void rmove();
#endif /* LOCAL2_H */
