#ifndef PFTN2_H
#define PFTN2_H
int talign();
int fixtype();
int fixclass();
int falloc();
int oalloc();
int hide();
int putbyte();
int lookup();
int beginit();
int nidcl();
int uclass();
int doinit();
int endinit();
int irbrace();
int ilbrace();
int clearst();
#endif /* PFTN2_H */
